#define PROPERTY_MAXPOP3CONNECTIONS             PLATFORM_STRING("maxpop3connections")
#define PROPERTY_MAXSMTPCONNECTIONS             PLATFORM_STRING("maxsmtpconnections")
#define PROPERTY_MIRROREMAILADDRESS             PLATFORM_STRING("mirroremailaddress")
#define PROPERTY_AUTHALLOWPLAINTEXT             PLATFORM_STRING("authallowplaintext")
#define PROPERTY_IMAPAUTHALLOWPLAINTEXT         PLATFORM_STRING("ImapAuthAllowPlainText")
#define PROPERTY_ALLOWMAILFROMNULL              PLATFORM_STRING("allowmailfromnull")
#define PROPERTY_LOGDEVICE                      PLATFORM_STRING("logdevice")
#define PROPERTY_LOGGING                        PLATFORM_STRING("logging")
#define PROPERTY_SMTPNOOFTRIES                  PLATFORM_STRING("smtpnoofretries")
#define PROPERTY_SMTPMINUTESBETWEEN             PLATFORM_STRING("smtpminutesbetweenretries")
#define PROPERTY_WELCOMEIMAP                    PLATFORM_STRING("welcomeimap")
#define PROPERTY_WELCOMEPOP3                    PLATFORM_STRING("welcomepop3")
#define PROPERTY_WELCOMESMTP                    PLATFORM_STRING("welcomesmtp")
#define PROPERTY_SMTPRELAYER                    PLATFORM_STRING("smtprelayer")
#define PROPERTY_PROTOCOLSMTP                   PLATFORM_STRING("protocolsmtp")
#define PROPERTY_PROTOCOLPOP3                   PLATFORM_STRING("protocolpop3")
#define PROPERTY_PROTOCOLIMAP                   PLATFORM_STRING("protocolimap")
#define PROPERTY_LOGFORMAT                      PLATFORM_STRING("logformat")
#define PROPERTY_MAXDELIVERYTHREADS             PLATFORM_STRING("maxdelivertythreads")
#define PROPERTY_AV_CLAMWIN_ENABLE              PLATFORM_STRING("avclamwinenable")
#define PROPERTY_AV_CLAMWIN_EXEC                PLATFORM_STRING("avclamwinexec")
#define PROPERTY_AV_CLAMWIN_DB                  PLATFORM_STRING("avclamwindb")
#define PROPERTY_AV_NOTIFY_SENDER               PLATFORM_STRING("avnotifysender")
#define PROPERTY_AV_NOTIFY_RECEIVER             PLATFORM_STRING("avnotifyreceiver")
#define PROPERTY_AV_DELETE_INFC_EMAIL           PLATFORM_STRING("avdeleteinfectedemail")
#define PROPERTY_AV_ACTION                      PLATFORM_STRING("avaction")
#define PROPERTY_HOSTNAME                       PLATFORM_STRING("hostname")
#define PROPERTY_SMTPRELAYER_USERNAME           PLATFORM_STRING("smtprelayerusername")
#define PROPERTY_SMTPRELAYER_PASSWORD           PLATFORM_STRING("smtprelayerpassword")
#define PROPERTY_SMTPRELAYER_USEAUTH            PLATFORM_STRING("usesmtprelayerauthentication")
#define PROPERTY_SMTPRELAYER_PORT               PLATFORM_STRING("smtprelayerport")
#define PROPERTY_USESCRIPTSERVER                PLATFORM_STRING("usescriptserver")
#define PROPERTY_SCRIPTLANGUAGE                 PLATFORM_STRING("scriptlanguage")
#define PROPERTY_MAXMESSAGESIZE                 PLATFORM_STRING("maxmessagesize")
#define PROPERTY_USECACHE                       PLATFORM_STRING("usecache")
#define PROPERTY_DOMAINCACHETTL                 PLATFORM_STRING("domaincachettl")
#define PROPERTY_ACCOUNTCACHETTL                PLATFORM_STRING("accountcachettl")
#define PROPERTY_ALIASCACHETTL                  PLATFORM_STRING("aliascachettl")
#define PROPERTY_DISTRIBUTIONLISTCACHETTL       PLATFORM_STRING("distributionlistcachettl")
#define PROPERTY_GROUPCACHETTL                  PLATFORM_STRING("groupcachettl")
#define PROPERTY_AWSTATSENABLED                 PLATFORM_STRING("awstatsenabled")
#define PROPERTY_RULELOOPLIMIT                  PLATFORM_STRING("rulelooplimit")

#define PROPERTY_USECUSTOMSCANNER               PLATFORM_STRING("usecustomvirusscanner")
#define PROPERTY_CUSTOMSCANNEREXECUTABLE        PLATFORM_STRING("customvirusscannerexecutable")
#define PROPERTY_CUSTOMSCANNERRETURNVALUE       PLATFORM_STRING("customviursscannerreturnvalue")

#define PROPERTY_USESPF                         PLATFORM_STRING("usespf")
#define PROPERTY_USESPFSCORE                    PLATFORM_STRING("usespfscore")
#define PROPERTY_USEMXCHECK                     PLATFORM_STRING("usemxchecks")
#define PROPERTY_USEMXCHECKSCORE                PLATFORM_STRING("usemxchecksscore")
#define PROPERTY_AS_CHECKHOSTINHELO             PLATFORM_STRING("ascheckhostinhelo")
#define PROPERTY_AS_CHECKHOSTINHELOSCORE        PLATFORM_STRING("ascheckhostinheloscore")
#define PROPERTY_AS_CHECKPTR                    PLATFORM_STRING("ascheckptr")
#define PROPERTY_AS_CHECKPTRSCORE               PLATFORM_STRING("ascheckptrscore")

#define PROPERTY_BACKUPOPTIONS                  PLATFORM_STRING("backupoptions")
#define PROPERTY_BACKUPDESTINATION              PLATFORM_STRING("backupdestination")

#define PROPERTY_DEFAULTDOMAIN                  PLATFORM_STRING("defaultdomain")
#define PROPERTY_AV_MAXMSGSIZE                  PLATFORM_STRING("avmaxmsgsize")
#define PROPERTY_SMTPDELIVERYBINDTOIP           PLATFORM_STRING("smtpdeliverybindtoip")
#define PROPERTY_ENABLEIMAPQUOTA                PLATFORM_STRING("enableimapquota")
#define PROPERTY_ENABLEIMAPIDLE                 PLATFORM_STRING("enableimapidle")
#define PROPERTY_ENABLEIMAPSORT                 PLATFORM_STRING("enableimapsort")
#define PROPERTY_ENABLEIMAPACL                  PLATFORM_STRING("enableimapacl")
#define PROPERTY_MAXIMAPCONNECTIONS             PLATFORM_STRING("maximapconnections")
#define PROPERTY_WORKERTHREADPRIORITY           PLATFORM_STRING("workerthreadpriority")

#define PROPERTY_TCPIPTHREADS                   PLATFORM_STRING("tcpipthreads")
#define PROPERTY_ALLOWINCORRECTLINEENDINGS      PLATFORM_STRING("smtpallowincorrectlineendings")
#define PROPERTY_MAXSMTPRECIPIENTSINBATCH       PLATFORM_STRING("maxsmtprecipientsinbatch")
#define PROPERTY_IMAPPUBLICFOLDERNAME           PLATFORM_STRING("imappublicfoldername")

#define PROPERTY_USEGREYLISTING                 PLATFORM_STRING("usegreylisting")
#define PROPERTY_GL_INITIALDELAY                PLATFORM_STRING("greylistinginitialdelay")
#define PROPERTY_GL_INITIALDELETE               PLATFORM_STRING("greylistinginitialdelete")
#define PROPERTY_GL_FINALDELETE                 PLATFORM_STRING("greylistingfinaldelete")

#define PROPERTY_AS_ADDHEADERSPAM               PLATFORM_STRING("antispamaddheaderspam")
#define PROPERTY_AS_ADDHEADERREASON             PLATFORM_STRING("antispamaddheaderreason")
#define PROPERTY_AS_PREPENDSUBJECT              PLATFORM_STRING("antispamprependsubject")
#define PROPERTY_AS_PREPENDSUBJECTTEXT          PLATFORM_STRING("antispamprependsubjecttext")
#define PROPERTY_AS_MAX_SIZE                    PLATFORM_STRING("antispammaxsize")

#define PROPERTY_ENABLEATTACHMENTBLOCKING       PLATFORM_STRING("enableattachmentblocking")
#define PROPERTY_SMTPDISCONNECTINVALIDCLIENTS   PLATFORM_STRING("disconnectinvalidclients")
#define PROPERTY_SMTPMAXINCORRECTCOMMANDS       PLATFORM_STRING("maximumincorrectcommands")

#define PROPERTY_SMTPRELAYERCONNECTIONSECURITY  PLATFORM_STRING("smtprelayerconnectionsecurity")

#define PROPERTY_ADDDELIVEREDTOHEADER           PLATFORM_STRING("adddeliveredtoheader")

#define PROPERTY_SPAMDELETETHRESHOLD            PLATFORM_STRING("spamdeletethreshold")
#define PROPERTY_SPAMMARKTHRESHOLD              PLATFORM_STRING("spammarkthreshold")

#define PROPERTY_SPAMASSASSIN_ENABLED           PLATFORM_STRING("spamassassinenabled")
#define PROPERTY_SPAMASSASSIN_SCORE             PLATFORM_STRING("spamassassinscore")
#define PROPERTY_SPAMASSASSIN_MERGE_SCORE       PLATFORM_STRING("spamassassinmergescore")
#define PROPERTY_SPAMASSASSIN_HOST              PLATFORM_STRING("spamassassinhost")
#define PROPERTY_SPAMASSASSIN_PORT              PLATFORM_STRING("spamassassinport")

#define PROPERTY_AS_DKIM_VERIFICATION_ENABLE          PLATFORM_STRING("ASDKIMVerificationEnabled")
#define PROPERTY_AS_DKIM_VERIFICATION_FAILURE_SCORE   PLATFORM_STRING("ASDKIMVerificationFailureScore")

#define PROPERTY_AUTOBAN_ENABLED                PLATFORM_STRING("AutoBanOnLogonFailureEnabled")
#define PROPERTY_MAX_INVALID_LOGON_ATTEMPTS     PLATFORM_STRING("MaxInvalidLogonAttempts")
#define PROPERTY_LOGON_ATTEMPTS_WITHIN          PLATFORM_STRING("LogonAttemptsWithinMinutes")
#define PROPERTY_AUTOBAN_MINUTES                PLATFORM_STRING("AutoBanMinutes")

#define PROPERTY_IMAP_HIERARCHY_DELIMITER       PLATFORM_STRING("IMAPHierarchyDelimiter")
#define PROPERTY_MESSAGE_INDEXING               PLATFORM_STRING("MessageIndexing")
#define PROPERTY_MAX_NUMBER_OF_ASYNC_TASKS      PLATFORM_STRING("MaxNumberOfAsynchronousTasks")

#define PROPERTY_BYPASS_GREYLISTING_ON_SPFSUCCESS  PLATFORM_STRING("BypassGreylistingOnSPFSuccess")
#define PROPERTY_BYPASS_GREYLISTING_ON_MAILFROMMX  PLATFORM_STRING("BypassGreylistingOnMailFromMX")

#define PROPERTY_MAX_NUMBER_OF_MXHOSTS          PLATFORM_STRING("MaxNumberOfMXHosts")
#define PROPERTY_SMTPCONNECTIONSECURITY         PLATFORM_STRING("SmtpDeliveryConnectionSecurity")
#define PROPERTY_VERIFYREMOTESSLCERTIFICATE     PLATFORM_STRING("VerifyRemoteSslCertificate")

#define PROPERTY_SSLCIPHERLIST PLATFORM_STRING("SslCipherList")
#define PROPERTY_SSLVERSIONS PLATFORM_STRING("SslVersions")

#define PROPERTY_CLAMAV_ENABLED              PLATFORM_STRING("ClamAVEnabled")
#define PROPERTY_CLAMAV_HOST                 PLATFORM_STRING("ClamAVHost")
#define PROPERTY_CLAMAV_PORT                 PLATFORM_STRING("ClamAVPort")

#define PROPERTY_IMAPMASTERUSER                PLATFORM_STRING("ImapMasterUser")
#define PROPERTY_ENABLEIMAPSASLPLAIN           PLATFORM_STRING("EnableImapSASLPlain")
#define PROPERTY_ENABLEIMAPSASLINTIALRESPONSE  PLATFORM_STRING("EnableImapSASLInitialResponse")

#define PROPERTY_IPV6_PREFERRED  PLATFORM_STRING("IPv6Preferred")

#define REQUIRED_DB_VERSION            5704